### ISSUE TITLE
Set-and-forget hotbar slot positioning for all jobs and UI layouts

### ISSUE THREAD

**Issue by alecaster** [MidoriKami/HotbarUnlimited#4]
If possible, this would help cut down the time of having to re-adjust the same hotbar slot positions on every job and different UI layouts, specially for situations where you may change it quite often to adapt and adjust further.

- i.e. I'm using Hotbar 9 that is a shared hotbar for ease of access to certain buttons and mounts. HBU facilitates my UI customization, however I have to adjust the same slots on every job and UI layout to keep it consistent as the image below. 
(quick mention: I'm unable to use extra hotbars for that purpose as every one is being used in one way or another)

![image](https://github.com/MidoriKami/HotbarUnlimited/assets/157773888/7e59eee2-5556-4d78-94fa-b7718405d861)

**Comment by MidoriKami** [comment]
I could probably implement a export/import feature for each slot and for each container, I'll think on this a bit before I do anything.
