### ISSUE TITLE
Hotbars moved through HUD Layout menu don't inherit container position in HBU

### ISSUE THREAD

**Issue by GaryFaceman** [MidoriKami/HotbarUnlimited#5]
When moving a hotbar through Main Menu -> HUD Layout, the container position in HotbarUnlimited for the moved hotbar is not updated accordingly, causing hotbars to snap back to their previous position. Since HBU saves hotbar positions on a per-job basis, this means having to manually move the hotbar across all jobs manually (either via number input or by resetting the job and moving everything back into position).

**Comment by MidoriKami** [comment]
Moving hotbars via hudlayout while the plugin is enabled is not and will not be supported.
